name: TpaPlugin
version: '${project.version}'
main: me.luckdeh.tpaplugin.TpaPlugin
api-version: '1.20'
commands:
  tpahere:
    description: tpahere
    permission: tpa.here
  tpdeny:
    description: tpdeny
    permission: tpa.deny
  tpa:
    description: tpa
    permission: tpa.tpa
  tpaccept:
    description: tpaccept
    permission: tpa.accept