name: TpaPlugin
version: '1.0-SNAPSHOT'
main: me.luckdeh.tpaplugin.TpaPlugin
api-version: '1.20'
commands:
  tpdeny:
    description: Tpdeny
    permission: tpa.deny
  tpa:
    description: Tpa
    permission: tpa.tpa
  tpaccept:
    description: Tpaccept
    permission: tpa.accept